// Zoom Pinch
export const CAMERA_MAX_ZOOM = 0.6;
export const CAMERA_MIN_ZOOM = 0.001;
export const CAMERA_ZOOM_PINCH_ATTENUATION = 300;

// Zoom Slider
export const CAMERA_SLIDER_HEIGHT = 200;
export const CAMERA_SLIDER_CIRCLE_VELOCITY_ATTENUATION = 80;

// Camera Bottom Bar
export const CAMERA_BOTTOM_BAR_HEIGHT = 168;

// Camera Filter Selection View
export const CAMERA_FILTER_SELECTION_FILTER_TILE_WIDTH = 48;
export const CAMERA_FILTER_SELECTION_FILTER_TILE_SELECTED_WIDTH = 64;
export const CAMERA_FILTER_SELECTION_FILTER_TILE_PADDING = 12;
